@startuml
skinparam sequence {
  ArrowThickness 2
  ParticipantFontSize 14
  ActorFontSize 14
}

actor Пользователь
participant Система

activate Пользователь

Пользователь -> Система: Вход в систему (Имя пользователя, Пароль)
activate Система
Система -> Система: Проверка данных пользователя
Система --> Пользователь: Успешный вход в систему

Пользователь -> Система: Чтение темы (Тема)
Система -> Система: Поиск информации о теме
Система -> Пользователь: Возврат информации о теме

Пользователь -> Система: Выполнение задания (Задание)
Система -> Система: Поиск информации о задании
Система -> Пользователь: Возврат информации о задании

Пользователь -> Система: Решение примера (Пример)
Система -> Система: Сохранение решения примера

Пользователь -> Система: Выход из системы
deactivate Пользователь
deactivate Система

@enduml
