@startuml

class Пользователи {
  + ID : int
  - Имя : String
  - Пароль : String
}

class Задания {
  + ID : int
  - Название : String
  - Дата_решения : Date
}

class Лекции {
  + ID : int
  - ID_задания : int
  - ID_примера : int
  - Дата_прочтения : Date
}

class Примеры {
  + ID : int
  - Название : String
  - Дата_решения : Date
  - Дата_прочтения : Date
}

class Прочитанные_лекции {
  - ID_пользователя : int
  - ID_лекции : int
}

class Решеные_задания {
  - ID_пользователя : int
  - ID_задание : int
}

class Прочитанные_примеры {
  - ID_пользователя : int
  - ID_задание : int
}

Пользователи "1" -- "n" Прочитанные_лекции
Лекции "1" -- "n" Прочитанные_лекции

Пользователи "1" -- "n" Решеные_задания
Задания "1" -- "n" Решеные_задания

Пользователи "1" -- "n" Прочитанные_примеры
Примеры "1" -- "n" Прочитанные_примеры

@enduml
